import { invoke } from "@tauri-apps/api/core";

export type Channel = {
  id: string;
  name: string;
  slug: string;
  active: boolean;
  background_count: number;
  subtitle_languages: string[];
  default_subtitle_preset_id: string | null;
  default_subtitle_preset: SubtitlePreset | null;
  thumbnail_mode: ThumbnailMode;
  ocr_languages: string[];
  default_thumbnail_preset_id: string | null;
  default_thumbnail_preset: ThumbnailPreset | null;
  thumbnail_preset_count: number;
  created_at: string;
  updated_at: string;
};

export type BackgroundAsset = {
  id: string;
  kind: "background";
  path: string;
  name: string;
  duration_seconds: number | null;
  width: number | null;
  height: number | null;
  frame_rate: number | null;
  codec: string | null;
  probe_status: "ready" | "tool_missing" | "probe_failed" | string;
  available: boolean;
  created_at: string;
  channel_ids?: string[];
};

export type BatchSummary = {
  id: string;
  name: string;
  workflow_mode: "render" | "download_only";
  output_root: string | null;
  state: "draft" | "confirmed";
  import_source: string;
  created_at: string;
  confirmed_at: string | null;
  job_count: number;
  ready_count: number;
  unresolved_count: number;
  thumbnail_mode_override: ThumbnailMode | null;
  thumbnail_preset_ids: string[];
  queue_queued_count: number;
  queue_running_count: number;
  queue_failed_count: number;
};

export type VideoJob = {
  id: string;
  batch_id: string;
  channel_id: string | null;
  channel_name: string;
  imported_channel_name: string;
  url: string;
  canonical_url: string | null;
  video_id: string | null;
  title: string | null;
  video_language: string | null;
  duration_seconds: number | null;
  thumbnail_url: string | null;
  metadata_status: "pending" | "ready" | "error";
  metadata_error: string | null;
  row_number: number;
  position: number;
  duplicate_of_job_id: string | null;
  background_asset_id: string | null;
  background_name: string | null;
  background_locked: boolean;
  background_available: boolean;
  background_pool_count: number;
  subtitle_languages: string[];
  subtitle_language_override: string[];
  subtitle_tracks: { creator: SubtitleTrack[]; automatic: SubtitleTrack[] };
  selected_subtitle_language: string | null;
  selected_subtitle_source: "creator" | "automatic" | "supplied_file" | null;
  subtitle_source: string | null;
  subtitle_decision: "unresolved" | "youtube" | "use_file" | "skip" | "needs_decision";
  supplied_subtitle_path: string | null;
  subtitle_error: string | null;
  subtitle_preset_id: string | null;
  subtitle_style: SubtitleStyle;
  subtitle_preset_name: string;
  available_subtitle_presets: SubtitlePreset[];
  include_video_source: boolean;
  source_audio_path: string | null;
  source_video_path: string | null;
  source_thumbnail_path: string | null;
  thumbnail_mode: ThumbnailMode;
  thumbnail_mode_override: ThumbnailMode | null;
  channel_thumbnail_mode: ThumbnailMode;
  thumbnail_preset_id: string | null;
  thumbnail_preset_locked: boolean;
  thumbnail_preset: ThumbnailPreset | null;
  available_thumbnail_presets: ThumbnailPreset[];
  thumbnail_ocr_text: string;
  thumbnail_ocr_confidence: number | null;
  thumbnail_ocr_languages: string[];
  thumbnail_ocr_status: "not_started" | "awaiting_confirmation" | "needs_review" | "confirmed" | "complete" | "manual" | "skipped" | "error" | string;
  thumbnail_progress: number | null;
  thumbnail_text: string;
  thumbnail_output_path: string | null;
  thumbnail_error: string | null;
  download_status: string;
  download_progress: number | null;
  download_error: string | null;
  queue_task: QueueTask | null;
  download_queue_task: JobQueueTask | null;
  thumbnail_queue_task: JobQueueTask | null;
  output_profile: OutputProfile;
  render_status: "not_started" | "rendering" | "complete" | "error" | string;
  render_error: string | null;
  render_progress: number | null;
  output_video_path: string | null;
  srt_sidecar_path: string | null;
  encoder_used: string | null;
  artifacts: JobArtifact[];
  flags: string[];
  readiness: string;
};

export type SubtitleTrack = { language: string; formats: string; label: string };
export type JobArtifact = { kind: string; path: string; available: boolean };
export type ThumbnailMode = "auto" | "manual" | "skip";
export type ThumbnailStyle = {
  background_type: "solid" | "gradient";
  background_color: string;
  gradient_end_color: string;
  gradient_angle: number;
  font_family: string;
  font_size: number;
  text_color: string;
  outline_color: string;
  outline_width: number;
  shadow: number;
  alignment: "left" | "center" | "right";
  position_x: number;
  position_y: number;
  max_width_percent: number;
  fit_mode: "shrink" | "wrap";
};
export type ThumbnailPreset = { id: string; owner_channel_id: string | null; name: string; style: ThumbnailStyle; created_at: string; updated_at: string };
export type OcrLanguage = { code: string; name: string };
export type SubtitleStyle = {
  font_family: string;
  bold: boolean;
  font_size: number;
  text_color: string;
  background_enabled: boolean;
  background_color: string;
  background_opacity: number;
  outline_color: string;
  outline_width: number;
  shadow: number;
  alignment: "top-left" | "top-center" | "top-right" | "middle-left" | "middle-center" | "middle-right" | "bottom-left" | "bottom-center" | "bottom-right";
  position_x: number;
  position_y: number;
};
export type SubtitlePreset = { id: string; channel_id: string | null; name: string; style: SubtitleStyle; created_at: string; updated_at: string };
export type SubtitleFontInfo = { font_family: string; available: boolean | null; matched_family: string | null; font_path: string | null; warning: string | null };
export type OutputProfile = { profile: "720p" | "match_background" | "custom"; frame_preference: "profile" | "background" | null; fit_mode: "crop" | "contain"; custom_width?: number; custom_height?: number; custom_frame_rate?: number };
export type RenderFrame = { width: number; height: number; frame_rate: number };
export type RenderPlan = { profile: string; background_frame: RenderFrame; profile_frame: RenderFrame; output_frame: RenderFrame; frame_preference: "profile" | "background" | null; fit_mode: "crop" | "contain"; has_frame_mismatch: boolean; requires_frame_decision: boolean; job: VideoJob };

export type BatchView = { batch: BatchSummary; jobs: VideoJob[] };
export type QueueLog = { level: string; message: string; created_at: string };
export type JobQueueTask = { id: string; state: string; stage: string; progress: number; error: string | null; created_at: string; updated_at: string };
export type QueueTask = {
  id: string;
  batch_id: string;
  job_id: string;
  title: string | null;
  video_id: string | null;
  pipeline: "video" | "thumbnail" | "download_only";
  state: string;
  stage: string;
  progress: number;
  output_root: string;
  output_folder_name: string | null;
  max_video_height: number | null;
  include_video_source: boolean;
  error: string | null;
  cancel_requested: boolean;
  created_at: string;
  started_at: string | null;
  updated_at: string;
  completed_at: string | null;
  logs?: QueueLog[];
};
export type QueueStatus = { tasks: QueueTask[]; counts: Record<string, number>; runtime: { state: string; worker_running: boolean; heartbeat_at: string | null; max_concurrency: number } };
export type ToolState = { version: string; ready: boolean; languages?: string[] };
export type LocalToolchainState = { ffmpeg: ToolState; ffprobe: ToolState; tesseract: ToolState; tessdata_dir: string };
export type DynamicToolState = { name: string; version: string; latest_version: string; updated: boolean; path: string };
export type DynamicToolchainState = { yt_dlp: DynamicToolState; deno: DynamicToolState };
export type YoutubeCookieSettings = { path: string | null; configured: boolean; available: boolean; valid_format: boolean };
export type OutputDirectorySettings = { path: string | null; configured: boolean; available: boolean };

export function workerRequest<T>(method: string, params: Record<string, unknown> = {}) {
  return invoke<T>("worker_request", { method, params });
}
